<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #000;
                font-size: 12pt;
            }
            .highlight {
                color: #dc143c;
            }
        </style>
    </head>
    <body>
        <h1>Hello</h1>
        <div class="subtitle">This us demo page using Slim 3 microframework for PHP</div>
        <p>This is <span class="highlight"><?=htmlspecialchars(isset($name) ? $name : 'home'); ?></span> page</p>
    </body>
</html>
