<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body{
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #000;
                font-size: 12pt;
            }
            input, select, button {
                color: #000;
                font-size: 12pt;
            }
            .error {
                color: #e00;
            }
            .highlight {
                color: #dc143c;
            }
        </style>
    </head>

    <body>
        <h1>Login</h1>
        <form name="login-form" method="post" action="/login">
            <div>
                <input name="email" type="text" placeholder="email">
            </div>
            <?php if($loginError) : ?>
            <div>
                <span name="login-error" class="error">Invalid login</span>
            </div>
            <?php endif ?>
            <div>
                <input name="password" type="password" placeholder="password">
            </div>
            <div>
                <input name="login" type="submit" value="Login">
            </div>
        </form>
    </body>
</html>
